import { ServiceRepositoryImpl } from '../infrastructure/repositories/ServiceRepositoryImpl';
import { ReservationRepositoryImpl } from '../infrastructure/repositories/ReservationRepositoryImpl';
import { NewsRepositoryImpl } from '../infrastructure/repositories/NewsRepositoryImpl';
import { UserRepositoryImpl } from '../infrastructure/repositories/UserRepositoryImpl';
import { OrganizationRepositoryImpl } from '../infrastructure/repositories/OrganizationRepositoryImpl';
import { ChatbotRepositoryImpl } from '../infrastructure/repositories/ChatbotRepositoryImpl';
import { ChatbotLogRepositoryImpl } from '../infrastructure/repositories/ChatbotLogRepositoryImpl';
import { ChatbotSessionRepositoryImpl } from '../infrastructure/repositories/ChatbotSessionRepositoryImpl';
import { TouristicAttractionRepositoryImpl } from '../infrastructure/repositories/TouristicAttractionRepositoryImpl';
import { AuditLogRepositoryImpl } from '../infrastructure/repositories/AuditLogRepositoryImpl';
import { ContactMessageRepositoryImpl } from '../infrastructure/repositories/ContactMessageRepositoryImpl';
import { ReviewRepositoryImpl } from '../infrastructure/repositories/ReviewRepositoryImpl';
import { RoleRepositoryImpl } from '../infrastructure/repositories/RoleRepositoryImpl';
import { ChatbotEmbeddingRepositoryImpl } from '../infrastructure/repositories/ChatbotEmbeddingRepositoryImpl';

import { ServiceUseCases } from '../application/use-cases/ServiceUseCases';
import { ReservationUseCases } from '../application/use-cases/ReservationUseCases';
import { NewsUseCases } from '../application/use-cases/NewsUseCases';
import { AuthUseCases } from '../application/use-cases/AuthUseCases';
import { OrganizationUseCases } from '../application/use-cases/OrganizationUseCases';
import { ChatbotUseCases } from '../application/use-cases/ChatbotUseCases';
import { TouristicAttractionUseCases } from '../application/use-cases/TouristicAttractionUseCases';
import { UploadUseCases } from '../application/use-cases/UploadUseCases';
import { AuditUseCases } from '../application/use-cases/AuditUseCases';
import { ContactUseCases } from '../application/use-cases/ContactUseCases';
import { ReviewUseCases } from '../application/use-cases/ReviewUseCases';
import { RoleUseCases } from '../application/use-cases/RoleUseCases';
import { ReminderScheduler } from '../infrastructure/scheduler/reminderScheduler';
import { SessionCleanupScheduler } from '../infrastructure/scheduler/sessionCleanupScheduler';

import { NodemailerMailService } from '../infrastructure/mail/NodemailerMailService';
import { GeminiService } from '../infrastructure/ai/GeminiService';
import { EmbeddingService } from '../infrastructure/ai/EmbeddingService';
import { CloudinaryUploadService } from '../infrastructure/services/CloudinaryUploadService';
import { BcryptPasswordHasher } from '../infrastructure/services/BcryptPasswordHasher';
import { JwtTokenService } from '../infrastructure/services/JwtTokenService';
import { AuditLoggerImpl } from '../infrastructure/services/AuditLoggerImpl';
import { WebSocketNotifierImpl } from '../infrastructure/services/WebSocketNotifierImpl';
import { WinstonLogger } from '../infrastructure/services/WinstonLogger';
import { config } from '../shared/config/config';

import { ServiceController } from '../interfaces/http/controllers/ServiceController';
import { ReservationController } from '../interfaces/http/controllers/ReservationController';
import { NewsController } from '../interfaces/http/controllers/NewsController';
import { AuthController } from '../interfaces/http/controllers/AuthController';
import { OrganizationController } from '../interfaces/http/controllers/OrganizationController';
import { ChatbotController } from '../interfaces/http/controllers/ChatbotController';
import { TouristicAttractionController } from '../interfaces/http/controllers/TouristicAttractionController';
import { AuditController } from '../interfaces/http/controllers/AuditController';
import { ContactController } from '../interfaces/http/controllers/ContactController';
import { ReviewController } from '../interfaces/http/controllers/ReviewController';
import { UploadController } from '../interfaces/http/controllers/UploadController';
import { RoleController } from '../interfaces/http/controllers/RoleController';
import { createPermissionLoader } from '../interfaces/http/middlewares/permissionMiddleware';

const serviceRepo = new ServiceRepositoryImpl();
const reservationRepo = new ReservationRepositoryImpl();
const newsRepo = new NewsRepositoryImpl();
const userRepo = new UserRepositoryImpl();
const organizationRepo = new OrganizationRepositoryImpl();
const chatbotRepo = new ChatbotRepositoryImpl();
const chatbotLogRepo = new ChatbotLogRepositoryImpl();
const chatbotSessionRepo = new ChatbotSessionRepositoryImpl();
const attractionRepo = new TouristicAttractionRepositoryImpl();

const mailService = new NodemailerMailService();
const aiService = config.ai.geminiApiKey ? new GeminiService(config.ai.geminiApiKey) : undefined;
const embeddingService = aiService ? new EmbeddingService(aiService) : undefined;
const uploadService = new CloudinaryUploadService();
const auditLogRepo = new AuditLogRepositoryImpl();
const auditLogger = new AuditLoggerImpl(auditLogRepo);
const wsNotifier = new WebSocketNotifierImpl();
const contactMessageRepo = new ContactMessageRepositoryImpl();
const reviewRepo = new ReviewRepositoryImpl();
const roleRepo = new RoleRepositoryImpl();
const passwordHasher = new BcryptPasswordHasher();
const tokenService = new JwtTokenService();
const logger = new WinstonLogger();

const serviceUseCases = new ServiceUseCases(serviceRepo);
const reservationUseCases = new ReservationUseCases(reservationRepo, logger, organizationRepo, mailService, serviceRepo);
const newsUseCases = new NewsUseCases(newsRepo);
const authUseCases = new AuthUseCases(userRepo, passwordHasher, tokenService, logger, config.app.frontendUrl, mailService);
const organizationUseCases = new OrganizationUseCases(organizationRepo);
const chatbotEmbeddingRepo = new ChatbotEmbeddingRepositoryImpl();
const chatbotUseCases = new ChatbotUseCases(chatbotRepo, serviceRepo, organizationRepo, logger, aiService, chatbotLogRepo, chatbotSessionRepo, embeddingService, chatbotEmbeddingRepo, attractionRepo, newsRepo, reservationRepo);
const attractionUseCases = new TouristicAttractionUseCases(attractionRepo);
const uploadUseCases = new UploadUseCases(uploadService);
const auditUseCases = new AuditUseCases(auditLogRepo);
const contactUseCases = new ContactUseCases(contactMessageRepo, logger, organizationRepo, mailService);
const reviewUseCases = new ReviewUseCases(reviewRepo);
const roleUseCases = new RoleUseCases(roleRepo);

export const serviceController = new ServiceController(serviceUseCases, auditLogger, chatbotUseCases);
export const reservationController = new ReservationController(reservationUseCases, auditLogger, wsNotifier, serviceUseCases);
export const newsController = new NewsController(newsUseCases, auditLogger, chatbotUseCases);
export const authController = new AuthController(authUseCases, auditLogger);
export const organizationController = new OrganizationController(organizationUseCases, auditLogger);
export const chatbotController = new ChatbotController(chatbotUseCases, auditLogger);
export const attractionController = new TouristicAttractionController(attractionUseCases, auditLogger, chatbotUseCases);
export const uploadController = new UploadController(uploadUseCases);
export const auditController = new AuditController(auditUseCases);
export const contactController = new ContactController(contactUseCases, auditLogger, wsNotifier);
export const reviewController = new ReviewController(reviewUseCases);
export const roleController = new RoleController(roleUseCases, auditLogger);
export const loadPermissions = createPermissionLoader(roleRepo);

export const reminderScheduler = new ReminderScheduler(reservationRepo, mailService);
export const sessionCleanupScheduler = new SessionCleanupScheduler(chatbotSessionRepo);
